[app]
video_source = "siliconflow"
hide_config = false

[siliconflow]
api_key = "sk-bppchrqflzui"

[apimart]
api_key = "sk-s4L8pbVG60aMOt5"

[ui]
hide_log = false
language = "zh"
tts_server = "siliconflow"
font_name = "MicrosoftYaHeiBold.ttc"
text_fore_color = "#FFFFFF"
font_size = 60

[azure]

[app.podcast]
default_speaker_1_voice = "zh-CN-XiaoxiaoNeural-Female"
default_speaker_2_voice = "zh-CN-YunxiNeural-Male"
podcast_dialogue_style = "conversational"
max_dialogue_turns = 1
min_article_length = 50
max_article_length = 50000
