[app]
video_source = "MiniMax"
hide_config = false

[MiniMax]
api_key = "sk-api-u7DlDQ8T0hfJ-x4gZp3CGiBZlUo6sH0xm779M0b2eLCP89aTdp0mu4E"
base_url = "https://api.minimaxi.com/v1"
llm_model = "M2-her"
tts_model = "speech-2.6-hd"

[siliconflow]
api_key = "sk-bppchrqflzyzlzpubgmqeqhaaobswqniui"

[apimart]
api_key = "sk-s4L8pbVGNijeMo9hMM60aMOt5"

[bgm]
type = "random"
volume = 0.15

[ui]
hide_log = false
language = "zh"
tts_server = "siliconflow"
font_name = "MicrosoftYaHeiBold.ttc"
text_fore_color = "#FFFFFF"
font_size = 60

[azure]

[app.podcast]
default_speaker_1_voice = "zh-CN-XiaoxiaoNeural-Female"
default_speaker_2_voice = "zh-CN-YunxiNeural-Male"
podcast_dialogue_style = "conversational"
max_dialogue_turns = 1
min_article_length = 50
max_article_length = 50000
